tasks:
- task_id: task3_1
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S2380121,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S2380121
  allowed_tools: &id001
  - condition_search
  - lab_search
  - medicationrequest_create
  - medicationrequest_search
  - patient_search
  - procedure_create
  - procedure_search
  - vital_create
  - vital_search

- task_id: task3_10
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S2703270,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S2703270
  allowed_tools: *id001

- task_id: task3_11
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S2111822,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S2111822
  allowed_tools: *id001

- task_id: task3_12
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6541353,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6541353
  allowed_tools: *id001

- task_id: task3_13
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S0547588,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S0547588
  allowed_tools: *id001

- task_id: task3_14
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6534835,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6534835
  allowed_tools: *id001

- task_id: task3_15
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S3070524,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S3070524
  allowed_tools: *id001

- task_id: task3_16
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6192632,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6192632
  allowed_tools: *id001

- task_id: task3_17
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6538722,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6538722
  allowed_tools: *id001

- task_id: task3_18
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S1777769,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S1777769
  allowed_tools: *id001

- task_id: task3_19
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6537563,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6537563
  allowed_tools: *id001

- task_id: task3_2
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S1353305,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S1353305
  allowed_tools: *id001

- task_id: task3_20
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6222362,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6222362
  allowed_tools: *id001

- task_id: task3_21
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S3241217,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S3241217
  allowed_tools: *id001

- task_id: task3_22
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6329254,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6329254
  allowed_tools: *id001

- task_id: task3_23
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6549951,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6549951
  allowed_tools: *id001

- task_id: task3_24
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S2119664,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S2119664
  allowed_tools: *id001

- task_id: task3_25
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S1736710,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S1736710
  allowed_tools: *id001

- task_id: task3_26
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S1152319,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S1152319
  allowed_tools: *id001

- task_id: task3_27
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6550627,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6550627
  allowed_tools: *id001

- task_id: task3_28
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S1733937,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S1733937
  allowed_tools: *id001

- task_id: task3_29
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S3236936,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S3236936
  allowed_tools: *id001

- task_id: task3_3
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6352985,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6352985
  allowed_tools: *id001

- task_id: task3_30
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6531922,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6531922
  allowed_tools: *id001

- task_id: task3_4
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S3228213,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S3228213
  allowed_tools: *id001

- task_id: task3_5
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S1521703,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S1521703
  allowed_tools: *id001

- task_id: task3_6
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S6415739,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S6415739
  allowed_tools: *id001

- task_id: task3_7
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S1579803,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S1579803
  allowed_tools: *id001

- task_id: task3_8
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S2033286,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S2033286
  allowed_tools: *id001

- task_id: task3_9
  category: clinical_data_recording
  difficulty: medium
  instruction: 'I just measured the blood pressure for patient with MRN of S1986380,
    and it is "118/77 mmHg". Help me record it.


    Context: It''s 2023-11-13T10:15:00+00:00 now. The flowsheet ID for blood pressure
    is BP.'
  expected_answer: ''
  required_actions:
  - recording_patient_data
  split: std
  task_type: action
  backend_profile: fhir
  source_benchmark: medagentbench
  source_group: task3
  source_task_type: recording_patient_data
  eval_mrn: S1986380
  allowed_tools: *id001
