services:
  main:
    build:
      context: ..
      dockerfile: environment/Dockerfile
    volumes:
      - /home/qianchuliu/projects/MedCLI/scripts/mimic_report_gen/assets/mimic-cxr-jpg/2.1.0:/data/_src/jpg_root:rw
      - /home/qianchuliu/projects/MedCLI/scripts/mimic_report_gen/assets/mimic-cxr/2.1.0/extracted/p14213287:/data/_src/patient_reports:rw
    environment:
      - PYTHONUNBUFFERED=1
      - PN_USER=${PN_USER:-}
      - PN_PASS=${PN_PASS:-}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
