services:
  main:
    build:
      context: ..
      dockerfile: environment/Dockerfile
    volumes:
      - ${MEDCLI_TUMOR_PATH_TCGA_CACHE:-${HOME}/harbor-cache/tumor_area_selection_pathology/tcga}:/data/cache/tcga:rw
      - ${MEDCLI_TUMOR_PATH_CAMELYON_CACHE:-${HOME}/harbor-cache/tumor_area_selection_pathology/camelyon16/slides}:/data/cache/camelyon16/slides:rw
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 4G
