services:
  main:
    build:
      context: ..
      dockerfile: environment/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}-img
    volumes:
      - workspace-data:/workspace/data
    depends_on:
      bootstrap:
        condition: service_completed_successfully
    environment:
      - PYTHONUNBUFFERED=1

  bootstrap:
    image: ${COMPOSE_PROJECT_NAME}-img
    volumes:
      - /home/qianchuliu/projects/MedCLI/scripts/ct_abnormality/assets/raw_cache:/data/_cache:rw
      - ${HOME}/.cache/huggingface/token:/root/.cache/huggingface/token:ro
      - workspace-data:/workspace/data
    command: ["/bin/bash", "/bootstrap.sh"]

volumes:
  workspace-data:
