services:
  fhir:
    image: hapiproject/hapi:latest
    container_name: ehr-medagentbench-fhir
    ports:
      - "8080:8080"
    environment:
      hapi.fhir.server_address: "http://localhost:8080/fhir"
    restart: unless-stopped
